spring:
  application:
    name: sys-discovery-eureka
  profiles:
    active: peer1
  security:
    user:
      name: user
      password: security

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:security@localhost:8761/eureka/ #,http://user:security@localhost:8762/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${server.port}
    prefer-ip-address: true
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}

---
spring:
  profiles: peer1
server:
  port: 8761

---
spring:
  profiles: peer2
server:
  port: 8762