spring:
  application:
    name: app-example
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:security@localhost:8761/eureka/ #,http://user:security@localhost:8762/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${server.port}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
    response:
      enabled: true
ribbon:
  eager-load:
    enabled: true
  restclient:
    enabled: true

logging:
  level:
    web: debug
    com.netflix.loadbalancer: error
  file:
    max-history: 7
    max-size: 66MB
  path: /tmp/scerp/${spring.application.name}